[package]
name = "geoman"
version = "0.1.0"
edition = "2024"
authors = ["James Campbell"]

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/app/main.rs"
name = "geoman"


[dependencies]
actix-web = "4.11.0"
uuid = { version = "1.18.1", features = ["v4"] }
anyhow = "1.0.100"
strum = { version = "0.27.2", features = ["derive"] }
clerk-rs = { version = "0.4.1", features = ["actix"] }
config = "0.15.18"
derive = "1.0.0"
once_cell = "1.21.3"
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
dotenvy = "0.15.7"
tracing = "0.1.41"
tracing-bunyan-formatter = "0.3.10"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
tracing-log = "0.2.0"
tracing-actix-web = "0.7.19"

[dev-dependencies.reqwest]
version = "0.12.24"
features = ["cookies"]

[dev-dependencies]
tokio = { version = "1.48.0", features = ["sync"] }
