[workspace]
resolver = "3"
members = ["app", "domain", "ogc"]

[workspace.dependencies]
sqlx = { version = "0.8", features = [
    "runtime-tokio-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
] }
uuid = { version = "1.18", features = ["v4"] }
anyhow = "1.0"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
geojson = "0.24"
geo-types = "0.7"
utoipa = { version = "4.2.3", features = [
    "actix_extras",
] } # Cannot upgrade to 5 due to OpenAPI 3.1 breaking OGC test suit 
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
tracing = "0.1"
ogcapi-types = "0.3"
strum = "0.27"
