[package]
name = "geoman"
version = "0.1.0"
edition = "2024"
authors = ["James Campbell"]

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/app/main.rs"
name = "geoman"


[dependencies]
actix-web = "4.11.0"
uuid = { version = "1.18.1", features = ["v4"] }
anyhow = "1.0.100"
strum = { version = "0.27.2", features = ["derive"] }
clerk-rs = { version = "0.4.1", features = ["actix"] }
config = "0.15.18"
once_cell = "1.21.3"
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
dotenvy = "0.15.7"
tracing = "0.1.41"
tracing-bunyan-formatter = "0.3.10"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
tracing-log = "0.2.0"
tracing-actix-web = "0.7.19"
geojson = "0.24.2"
geo-types = "0.7.17"
utoipa = { version = "5.3.0", features = ["actix_extras"] }
utoipa-actix-web = "0.1.2"
utoipa-swagger-ui = { version = "9.0.2", features = ["actix-web"] }
serde_with = "3.15.1"
sqlx = { version = "0.8.6", features = [
    "runtime-tokio-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
] }
log = "0.4.28"
slug = "0.1.6"
derive_more = { version = "2.0.1", features = ["as_ref"] }


[dev-dependencies.reqwest]
version = "0.12.24"

[dev-dependencies]
rand = "0.9.2"

tokio = { version = "1.48.0", features = ["sync"] }
