health_check: "/health-check"
health_check_authenticated: "/health-check-authenticated"

api:
  base: "/api"
  keys: "/keys"
  projects: "/projects"
  users: "/users"
  collections: "/collections"
  app_settings: "/app-settings"

docs:
  base: "/docs"

ogc_api:
  base: "/ogcapi"
  conformance_declaration: "/conformance"
  collections: "/collections"
  project: "/project"
  openapi: "/openapi.json"

webhooks:
  base: "/webhooks"
  clerk: "/clerk"
