health_check: "/health-check"
health_check_authenticated: "/health-check-authenticated"

api:
  base: "/api"

docs:
  base: "/docs"
  api: "/openapi.json"

ogc_api:
  base: "/ogcapi"
  conformance_declaration: "/conformance"
  collections: "/collections"
