health_check: "/health-check"
health_check_authenticated: "/health-check-authenticated"

api:
  base: "/api"
  keys: "/keys"
  projects: "/projects"
  users: "/users"
  current_user: "/current"

docs:
  base: "/docs"

ogc_api:
  base: "/ogcapi"
  conformance_declaration: "/conformance"
  collections: "/collections"
  project: "/project"
  openapi: "/openapi.json"

